### PR TITLE
[RAC-6591] init version file for version bump schema

### PR DESCRIPTION
**Pull request by AlaricChan**
**Background**
As a core part of the transition from bamboo to concourse, we brought in version file to control bumping version, and parameterized the referenced jar version of SMI lib in SMI service build.gradle. So, we initiated the version number with released latest version.

**Details**
Add version file, set version number to the latest version released by bamboo system (searched from maven central).

**Reviewer**
@michaelsteven  @leoyjchang @yaolingling @lanchongyizu

### CODE REVIEW

**Review by yaolingling — APPROVED** [review]

**Review by michaelsteven — APPROVED** [review]
looks good

**Comment by AlaricChan** [comment]
Removed maven build and test in travis ci.
@michaelsteven @lanchongyizu

**Comment by lanchongyizu** [comment]
@AlaricChan We could change `mvn build test sonarqube` to `gradle build test` in .travis.yml, and add `sonarqube `later when we got the token of sonarqube from @michaelsteven.

**Review by lanchongyizu — APPROVED** [review]

**Comment by AlaricChan** [comment]
Agree with suggestion @lanchongyizu. 
It does not make sense to directoly place password of sonarqube into gradle.properties. Besides, the password of sonarqube is stored in vault server, we did not found any solution to combine vault server with travis.
So for now, I changed `mvn build test sonarqube` to `gradle build test`. 
@michaelsteven @yaolingling

**Pull request merged**
